id = "rust-glancer"
name = "Rust Glancer"
description = "Low-memory Rust language server"
version = "0.2.0" # x-release-please-version
schema_version = 1
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
repository = "https://github.com/rust-glancer/rust-glancer"

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["rust-glancer", "rust-glancer", "releases", "download", "**"]

[language_servers.rust-glancer]
name = "Rust Glancer"
languages = ["Rust"]
